In [1]:
import numpy as np

Create numpy array

In [101]:
array1 = np.array([1,2,3,4,5,6,7,8])
array2 = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
#array3 = np.array([[[1,2],[3,4]] , [[5,6],[7,8]]]) 3-dimensonal array can be created like this.

Informations about array

In [65]:
print("Dimension of array1 is "+ str(array1.ndim))
print("Dimension of array2 is "+ str(array2.ndim) )

Dimension of array1 is 1
Dimension of array2 is 2


In [66]:
print("Shape of array1 is (rows,columns)"+ str(array1.shape))
print("Shape of array2 is (rows,columns)"+ str(array2.shape))

Shape of array1 is (rows,columns)(8,)
Shape of array2 is (rows,columns)(2, 8)


In [67]:
print("Data types of array1 is "+ str(array1.dtype))
print("Data types array2 is "+ str(array2.dtype))

Data types of array1 is int32
Data types array2 is int32


In [68]:
print("Item size of array1 is "+ str(array1.itemsize) + ' bytes')
print("Item size array2 is "+ str(array2.itemsize)+ ' bytes')

Item size of array1 is 4 bytes
Item size array2 is 4 bytes


In [69]:
print("Size of array1 is "+ str(array1.size*array1.itemsize) + ' bytes')
print("Size array2 is "+ str(array2.size*array2.itemsize)+ ' bytes')

Size of array1 is 32 bytes
Size array2 is 64 bytes


In [70]:
print("Total size of array1 is "+ str(array1.size) + ' elements')
print("Total size array2 is "+ str(array2.size)+ ' elements')

Total size of array1 is 8 elements
Total size array2 is 16 elements


Get specific element from array

In [71]:
array1[0]

1

In [72]:
array1[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
array1[:2]

array([1, 2])

In [74]:
array1[:-1]

array([1, 2, 3, 4, 5, 6, 7])

In [75]:
array1[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [76]:
array1[0:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
array2[1,1]

10

In [78]:
array2[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
array2[0,:][1]

2

In [80]:
array2[:,1]

array([ 2, 10])

In [81]:
array1[0:6:2]

array([1, 3, 5])

In [84]:
array2[0,:][0:8:2]

array([1, 3, 5, 7])

In [93]:
array2[0,:][0:8:2]

array([1, 3, 5, 7])

Change array values

In [100]:
array1

array([1, 1, 1, 1, 1, 1, 1, 1])

In [102]:
array1[0] = 5
array1

array([5, 2, 3, 4, 5, 6, 7, 8])

In [103]:
array1[2:4] = 1
array1

array([5, 2, 1, 1, 5, 6, 7, 8])

In [104]:
array1[3:5] = [ 15,15]
array1

array([ 5,  2,  1, 15, 15,  6,  7,  8])

Some numpy methods

In [107]:
a = np.zeros(3)
print(type(a[0]))
a

<class 'numpy.float64'>


array([0., 0., 0.])

In [109]:
b = np.zeros(3,dtype='int32')
print(type(b[0]))
b

<class 'numpy.int32'>


array([0, 0, 0])

In [110]:
b.shape

(3,)

In [112]:
b.shape = (3,1)
b

array([[0],
       [0],
       [0]])

In [113]:
c = np.ones(5)
c

array([1., 1., 1., 1., 1.])

In [120]:
d = np.empty(5)
d

array([1., 1., 1., 1., 1.])

In [122]:
e = np.linspace(1,9,3) # create 3 element from 1 to 9
e

array([1., 5., 9.])

In [123]:
?e.shape

In [124]:
rand = np.random.randint(1,10,5)
rand

array([1, 1, 9, 5, 7])

In [142]:
np.random.seed(0) #seed makes the number predictoble
rand2 = np.random.randint(15 , size=5)
rand2

array([12,  5,  0,  3, 11])

In [143]:
f = np.full((2,3),15) 
f

array([[15, 15, 15],
       [15, 15, 15]])

In [144]:
g = np.full_like(f , 4)
g

array([[4, 4, 4],
       [4, 4, 4]])

In [184]:
ar = np.array([1,2,3])
h = np.repeat(ar , 3)
h

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [185]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [186]:
res = np.vstack([a1,a2])
res

array([[1, 2, 3],
       [4, 5, 6]])

In [187]:
res2 = np.vstack([a1,a2,a1,a2])
res2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [188]:
res3 = np.hstack([a1,a2])
res3

array([1, 2, 3, 4, 5, 6])

In [189]:
res4 = np.hstack([a1,a2,a1,a2])
res4

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

Adding,Substraction,Multiplication,Division

In [190]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])


In [191]:
np.sum(arr1)

6

In [192]:
np.max(arr2)

6

In [193]:
np.min(arr1)

1

In [194]:
arr1+arr2

array([5, 7, 9])

In [195]:
arr1 * arr2

array([ 4, 10, 18])

In [196]:
arr1 - arr2

array([-3, -3, -3])

In [197]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [199]:
#Matrix multiplication
m1 = np.random.randint(10,size=(3,4))
m1

array([[3, 7, 9, 3],
       [5, 2, 4, 7],
       [6, 8, 8, 1]])

In [202]:
m2 = np.random.randint(15,size=(4,2))
m2

array([[ 3,  0],
       [ 3,  5],
       [14,  0],
       [ 2,  3]])

In [203]:
result = np.matmul(m1,m2)
result

array([[162,  44],
       [ 91,  31],
       [156,  43]])

In [205]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [206]:
determinant = np.linalg.det(identity)
determinant

1.0

and more ...